@echo off
rem # Script for updating the Minecraft patch.
rem # Requires a repository with the Minecraft source code in the "mc" folder
rem # next to "src".
rem # Branches in that repo must be set up as follows:
rem # master: vanilla Minecraft code, as generated by the MCP.
rem # modded: modified Minecraft code, as generated by the apply-patch script.

cd ..\mc
git checkout master
git checkout -b tmp
git merge --squash modded
git commit -a -m "mod"
git format-patch master --ignore-space-change
git checkout modded
git branch -D tmp
move /Y 0001-mod.patch ..\patch\minecraft.patch
rem pause